on:
  release:
    types: [created]

jobs:
  release:
    name: Build release assets
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu}
          - {os: ubuntu-latest, toolchain: stable, target: aarch64-unknown-linux-gnu}
          - {os: ubuntu-latest, toolchain: stable, target: arm-unknown-linux-gnueabi}
          - {os: ubuntu-latest, toolchain: stable, target: armv7-unknown-linux-gnueabihf}
          - {os: ubuntu-latest, toolchain: stable,  target: x86_64-unknown-linux-musl}
          - {os: macos-latest,   toolchain: stable, target: x86_64-apple-darwin}
          - {os: windows-latest, toolchain: stable-x86_64-pc-windows-gnu, target: x86_64-pc-windows-gnu}
          - {os: windows-latest, toolchain: stable-x86_64-pc-windows-msvc, target: x86_64-pc-windows-msvc}
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.config.toolchain }}
          target: ${{ matrix.config.target }}
          override: true
          default: true

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build --all --release

      - name: Get tag name
        id: get_version
        run: echo ::set-output name=version::``${GITHUB_REF#refs/tags/}``
        shell: bash

      - name: Pack binaries if unix
        if: matrix.config.os != 'windows-latest'
        run: tar -C ./target/${{ matrix.config.target }}/release -czvf vergit-${{ steps.get_version.outputs.version }}-${{ matrix.config.target }}.tar.gz vergit

      - name: Pack binaries if windows
        if: matrix.config.os == 'windows-latest'
        run: compress-archive ./target/${{ matrix.config.target }}/release/vergit vergit-${{ steps.get_version.outputs.version }}-${{ matrix.config.target }}.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: vergit-${{ steps.get_version.outputs.version }}-${{ matrix.config.target }}.*
          asset_name: vergit-${{ steps.get_version.outputs.version }}-${{ matrix.config.target }}
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true